1.5
js-tasks-ru/jsbasic-20240219_dg-web pull request #3
Opened 2024-02-13 08:51 UTC by dmitriy-stakin

2024-02-13 08:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-02-13 09:45 UTC, koalex requested changes
Исправить замечание **1-5**

2024-02-13 09:45 UTC, koalex commented on 1-module/5-task/index.js
> +  return (str.length > maxlength) ? str.slice(0,maxlength).replace(/.$/,"...") : str
Здесь нужно не 3 точки, а символ троеточие. Его можно скопировать из текста [задачи](https://learn.javascript.ru/taskbook/jsbasic-20240219/workspace/1-module/5-task) (написано внизу).

2024-02-13 12:41 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-02-14 05:50 UTC, koalex approved these changes

2024-02-14 05:50 UTC, merged